server:
  port: 9999
  error:
    include-message: always
    include-binding-errors: always

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quizhorniw/spring-cloud-configuration
          timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
